---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mso4sc-high-level-view/mso4sc-high-level-view.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/142194/articles/286939/master/file/figures/mso4sc-high-level-view/mso4sc-high-level-view.png"
    folder_url: "/users/142194/articles/286939/master/folder/figures/mso4sc-high-level-view"
